# Generated by Django 3.2 on 2025-07-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_producttype_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
