# Generated by Django 3.2 on 2025-07-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20250727_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='mood',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Happy'), (1, 'Sad'), (3, 'Fear')]),
        ),
    ]
